[build]
  # Diretório que contém os arquivos de build do frontend
  base = "frontend"
  publish = "build"
  command = "npm run build"

# Configuração de variáveis de ambiente para o frontend
[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

# Configuração para o backend como função serverless
[functions]
  directory = "backend"

# Redirecionamentos para o SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecionamentos para a API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
